DATABASE_URL = 'sqlite:///database.db'
BASE_URL = ''
HASH_ALOGRITHM = 'HS256'
SECRET_KEY = 'gxdp8-kygcw-m4fgh-pqp3d-brdjg'
ALLOWED_HOSTS = ['*']
ACCESS_TOKEN_EXPIRE_TIME_MINUTES = 30
SHOW_ERROR_IN_CODE = True
ERROR_OCCURED = 'Error Occured: {}'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USER = 'piratesmailservice@gmail.com'
EMAIL_PASSWORD = '2ceinwar'